// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager2;

#nullable disable

namespace TaskManager2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("TaskManager2.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Description = "This is Task 1",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2195),
                            IsCompleted = true,
                            Title = "Tesk 1"
                        },
                        new
                        {
                            TaskId = 2,
                            Description = "This is Task 2",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2232),
                            IsCompleted = true,
                            Title = "Tesk 2"
                        },
                        new
                        {
                            TaskId = 3,
                            Description = "This is Task 3",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2234),
                            IsCompleted = true,
                            Title = "Tesk 3"
                        },
                        new
                        {
                            TaskId = 4,
                            Description = "This is Task 4",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2235),
                            IsCompleted = true,
                            Title = "Tesk 4"
                        },
                        new
                        {
                            TaskId = 5,
                            Description = "This is Task 5",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2236),
                            IsCompleted = true,
                            Title = "Tesk 5"
                        },
                        new
                        {
                            TaskId = 6,
                            Description = "This is Task 6",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2238),
                            IsCompleted = true,
                            Title = "Tesk 6"
                        },
                        new
                        {
                            TaskId = 7,
                            Description = "This is Task 7",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2239),
                            IsCompleted = true,
                            Title = "Tesk 7"
                        },
                        new
                        {
                            TaskId = 8,
                            Description = "This is Task 8",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2240),
                            IsCompleted = true,
                            Title = "Tesk 8"
                        },
                        new
                        {
                            TaskId = 9,
                            Description = "This is Task 9",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2240),
                            IsCompleted = true,
                            Title = "Tesk 9"
                        },
                        new
                        {
                            TaskId = 10,
                            Description = "This is Task 10",
                            DueDate = new DateTime(2023, 9, 24, 21, 49, 32, 919, DateTimeKind.Local).AddTicks(2242),
                            IsCompleted = true,
                            Title = "Tesk 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
